<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="row">
        <div class="col-md-4 offset-md-4 col-lg-4 offset-lg-4">
            <div class="alert alert-success text-center" role="alert">
                <p><i class="fa fa-refresh fa-spin fa-5x fa-fw"></i></p>
                <p><?php _e('Please wait to sync process finished'); ?></p>
                <p><?php echo $this->escape($url); ?></p>
            </div>
        </div>
    </div>
    <script>
        window.setTimeout(function () {
            window.location.href = '<?php echo $this->escape($url); ?>';
        }, 500);
    </script>
</div>