<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class='clearfix'>

    <div class="alert alert-success" role="alert">
        <div class="row">
            <div class="col-lg-10 col-md-10">
                <?php _e('You can sync website visit actions here, all syncs finished to yesterday and your synced data have one day delay'); ?>
            </div>
            <div class="col-lg-2 col-md-2 text-right">
                <a class="btn btn-success" href="<?php echo $this->escape($url); ?>" role="button">
                    <i class="fa fa-refresh"></i>
                    <?php _e('Start sync'); ?>
                </a>
            </div>
        </div>
    </div>

    <div class='clearfix'>
        <ul class="nav nav-tabs" id="statisticsTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="hourly-tab" data-toggle="tab" href="#hourly" role="tab" aria-controls="hourly" aria-selected="true">
                    <?php _e('Hourly statistics'); ?>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="daily-tab" data-toggle="tab" href="#daily" role="tab" aria-controls="daily" aria-selected="false">
                    <?php _e('Daily statistics'); ?>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="monthly-tab" data-toggle="tab" href="#monthly" role="tab" aria-controls="monthly" aria-selected="false">
                    <?php _e('Monthly statistics'); ?>
                </a>
            </li>
        </ul>
        <div class="tab-content" id="statisticsTabContent">
            <div class="tab-pane fade show active" id="hourly" role="tabpanel" aria-labelledby="hourly-tab">
                <?php echo $this->chart('line', $data['hourly']); ?>
            </div>
            <div class="tab-pane fade" id="daily" role="tabpanel" aria-labelledby="daily-tab">
                <?php echo $this->chart('line', $data['daily']); ?>
            </div>
            <div class="tab-pane fade" id="monthly" role="tabpanel" aria-labelledby="monthly-tab">
                <?php echo $this->chart('line', $data['monthly']); ?>
            </div>
        </div>
    </div>
</div>