<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class='clearfix'>
    <div class="alert alert-success" role="alert">
        <div class="row">
            <div class="col-md-10">
                <?php _e('You can try sync this item information'); ?>
            </div>
            <div class="col-md-2 text-right">
                <a class="btn btn-success" href="<?php echo $this->escape($url); ?>" role="button">
                    <i class="fa fa-refresh"></i>
                    <?php _e('Start sync'); ?>
                </a>
            </div>
        </div>
    </div>
    <div class='clearfix'>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
                <a href="#daily" aria-controls="daily" role="tab" data-toggle="tab">
                    <?php _e('Daily statistics'); ?>
                </a>
            </li>
            <li role="presentation">
                <a href="#monthly" aria-controls="monthly" role="tab" data-toggle="tab">
                    <?php _e('Monthly statistics'); ?>
                </a>
            </li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="daily">
                <?php echo $this->chart('line', $data['daily']); ?>
            </div>
            <div role="tabpanel" class="tab-pane" id="monthly">
                <?php echo $this->chart('line', $data['monthly']); ?>
            </div>
        </div>
    </div>
</div>