<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <?php if ($confirm) {  ?>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="alert alert-success text-center" role="alert">
                    <p><i class="fa fa-refresh fa-spin fa-5x fa-fw"></i></p>
                    <p><?php _e('Please wait to sync process finished'); ?></p>
                    <p><?php echo $this->escape($url); ?></p>
                </div>
            </div>
        </div>
        <script>
            window.setTimeout(function () {
                window.location.href = '<?php echo $this->escape($url); ?>';
            }, 500);
        </script>
    <?php } else { ?>
        <div class="alert alert-success" role="alert">
            <div class="row">
                <div class="col-md-10">
                    <?php _e('You can sync website visit actions here, all syncs finished to yesterday and your synced data have one day delay'); ?>
                </div>
                <div class="col-md-2 text-right">
                    <a class="btn btn-success" href="<?php echo $this->escape($url); ?>" role="button">
                        <i class="fa fa-refresh"></i>
                        <?php _e('Start sync'); ?>
                    </a>
                </div>
            </div>
        </div>
    <?php } ?>
</div>
